# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcorp_user',
            name='user_type',
            field=models.IntegerField(choices=[('House Owner', 1), ('Paying Guest', 2)], default=1),
            preserve_default=False,
        ),
    ]
