# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_pgcorp_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgcorp_user',
            name='user_type',
            field=models.CharField(choices=[('House Owner', 'house_owner'), ('Paying Guest', 'paying_guest')], max_length=20),
        ),
    ]
