# Generated by Django 2.1.7 on 2019-02-26 17:19

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20190213_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcorp_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.Pgcorp_user.save_to_profile_pic),
        ),
    ]
