# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-29 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlatDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nashik', 'Nashik')], max_length=30)),
                ('title', models.CharField(default='default', max_length=30)),
                ('hash', models.CharField(max_length=6)),
                ('rent', models.IntegerField()),
                ('slug', models.SlugField(null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flats.Flat')),
            ],
        ),
    ]
