# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-19 08:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteFlats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FlatApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiation_price', models.IntegerField(default=0, help_text='Enter the total rent that you wish to have', validators=[django.core.validators.MinValueValidator(limit_value=100)])),
                ('negotiation_number_of_guests', models.IntegerField(default=1, help_text='Enter the total rent that you wish to have', validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('allowed_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlatDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('total_space', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=50)])),
                ('total_rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=200)])),
                ('deposit', models.CharField(max_length=10)),
                ('possession', models.CharField(max_length=20)),
                ('total_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('property_type', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=4)),
                ('parking_options', models.CharField(default='No Parking', max_length=30)),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('hash', models.CharField(max_length=6)),
                ('slug', models.SlugField(null=True)),
                ('date_of_posting', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flat_images/')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Flats.FlatDetails')),
            ],
        ),
        migrations.AddField(
            model_name='flatapplication',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flats.FlatDetails'),
        ),
        migrations.AddField(
            model_name='flatapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favouriteflats',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flats.FlatDetails'),
        ),
        migrations.AddField(
            model_name='favouriteflats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
