# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatdetails',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
