# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 10:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetails',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flatdetails',
            name='rent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=200)]),
        ),
    ]
