# Generated by Django 2.1.4 on 2019-02-15 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0002_auto_20190213_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatdetails',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='flatdetails',
            old_name='rent',
            new_name='total_rent',
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='deposit',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='description',
            field=models.CharField(default='Enter some description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='floor',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='number_of_guests',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='possession',
            field=models.CharField(default='Immediately', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='property_type',
            field=models.CharField(default='Apartment', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='total_rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatdetails',
            name='total_space',
            field=models.CharField(default='300sqft', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flatdetails',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
