# Generated by Django 2.1.7 on 2019-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0003_auto_20190215_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatdetails',
            name='parking_options',
            field=models.CharField(default='No Parking', max_length=30),
        ),
    ]
