# Generated by Django 2.1.7 on 2019-02-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0004_flatdetails_parking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatdetails',
            name='parking',
        ),
    ]
