# Generated by Django 2.1.7 on 2019-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0006_auto_20190215_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetails',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
