# Generated by Django 2.1.7 on 2019-02-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0008_favouriteflats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatdetails',
            old_name='datetime',
            new_name='date_of_posting',
        ),
    ]
