# Generated by Django 2.1.7 on 2019-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0010_auto_20190218_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetails',
            name='date_of_posting',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
