# Generated by Django 2.1.7 on 2019-02-18 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0011_auto_20190218_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetails',
            name='total_space',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=50)]),
        ),
    ]
