# Generated by Django 2.1.7 on 2019-04-13 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flats', '0014_flatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatimage',
            name='flat',
        ),
        migrations.AddField(
            model_name='flatapplication',
            name='negotiation_number_of_guests',
            field=models.IntegerField(default=1, help_text='Enter the total rent that you wish to have', validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AddField(
            model_name='flatapplication',
            name='negotiation_price',
            field=models.IntegerField(default=0, help_text='Enter the total rent that you wish to have', validators=[django.core.validators.MinValueValidator(limit_value=100)]),
        ),
    ]
